name: asyste
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.2
  equatable:
  dio: ^3.0.10

  
    #camera:
    #path_provider:
    #path:


  cupertino_icons: ^0.1.3
  webview_flutter: ^0.3.20+2
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

